server:
  port: 8081

spring:
  application:
    name: rabbitmq-listener

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: myFanoutQueue
  exchange:
    name: myFanoutExchange
    durable: true